In [1]:
import numpy as np
import pandas as pd
import sklearn as sk
from sklearn.ensemble import IsolationForest
from sklearn.model_selection import TimeSeriesSplit

Data Exploration and Preprocessing

In [2]:
data = pd.read_csv('data/AABA_2006-01-01_to_2018-01-01.csv')
data.describe()

              Open         High          Low        Close        Volume
count  3019.000000  3019.000000  3019.000000  3019.000000  3.019000e+03
mean     28.426479    28.766532    28.066558    28.412726  2.158391e+07
std      13.257242    13.356692    13.157326    13.258163  1.926231e+07
min       9.100000     9.480000     8.940000     8.950000  1.939061e+06
25%      16.175000    16.385000    15.970000    16.130000  1.248025e+07
50%      27.180000    27.490000    26.820000    27.100000  1.732130e+07
75%      36.655000    37.035000    36.305000    36.635000  2.512757e+07
max      73.020000    73.250000    72.460000    72.930000  4.382317e+08

In [3]:
data.head(5)

         Date   Open   High    Low  Close    Volume  Name
0  2006-01-03  39.69  41.22  38.79  40.91  24232729  AABA
1  2006-01-04  41.22  41.90  40.77  40.97  20553479  AABA
2  2006-01-05  40.93  41.73  40.85  41.53  12829610  AABA
3  2006-01-06  42.88  43.57  42.80  43.21  29422828  AABA
4  2006-01-09  43.10  43.66  42.82  43.42  16268338  AABA

In [4]:
data = data[data['Date'] > '2010-01-01']
data.head(5)

            Date   Open   High    Low  Close    Volume  Name
1007  2010-01-04  16.94  17.20  16.88  17.10  16588957  AABA
1008  2010-01-05  17.22  17.23  17.00  17.23  11718126  AABA
1009  2010-01-06  17.17  17.30  17.07  17.17  16421960  AABA
1010  2010-01-07  16.81  16.90  16.57  16.70  31816301  AABA
1011  2010-01-08  16.68  16.76  16.62  16.70  15471074  AABA

In [5]:
data.shape

(2012, 7)

Split into Train, Test, and Validation Sets

In [6]:
cv_splits = TimeSeriesSplit(n_splits=5)

Feature Engineering

In [7]:
# # Cross Validation Loop
# for train_index, test_index in cv_splits.split(data):
#     X_train, X_test = data.iloc[train_index], data.iloc[test_index]

#     # Feature Engineering


#     # Model Training
#     model = IsolationForest()
#     model.fit(X_train)